name: Deploy to Local Server

on:
  push:
    branches:
      - main  # Укажите вашу основную ветку

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Update repository and restart Node.js app
      run: |
        ssh oit@192.168.3.228 '
          cd /home/oit/baza && \
          git pull origin main && \
          fuser -k 3021/tcp || true && \  # Убивает процесс на порту 3021
          nohup node server.js &           # Запускает сервер заново в фоновом режиме
        '
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}



